import type { Product } from "./types";
// Illustrative launch catalog. Replace with your own inventory before accepting live orders.
const rows = [
  [
    "studio-headphones",
    "Studio Wireless Headphones",
    "Electronics",
    43500,
    58000,
    "headphones",
    true,
    true,
    false,
    "#eee9e1",
    4.9,
    128,
    "Immersive sound, without the noise. A comfortable everyday companion with active noise cancellation and up to 40 hours of listening.",
    [
      "Active noise cancellation",
      "Up to 40-hour battery",
      "USB-C charging",
      "Foldable, comfortable design",
    ],
  ],
  [
    "everyday-tote",
    "The Everyday Leather Tote",
    "Fashion",
    32500,
    45000,
    "bag",
    true,
    true,
    false,
    "#eae4d9",
    4.8,
    86,
    "Your day, beautifully carried. A structured vegan leather tote with a roomy interior, magnetic closure, and timeless silhouette.",
    [
      "Premium vegan leather",
      "Room for a 13-inch laptop",
      "Interior zip pocket",
      "Adjustable shoulder strap",
    ],
  ],
  [
    "ceramic-table-lamp",
    "Nordic Ceramic Table Lamp",
    "Home & Living",
    28500,
    38000,
    "lamp",
    true,
    false,
    true,
    "#eeeae3",
    4.7,
    54,
    "A little warmth for your favourite corner. A sculptural ceramic base and linen shade bring soft, ambient light to any room.",
    [
      "Hand-finished ceramic base",
      "Warm ambient lighting",
      "Linen fabric shade",
      "LED bulb included",
    ],
  ],
  [
    "court-sneakers",
    "Everyday Court Sneakers",
    "Fashion",
    24000,
    32000,
    "sneakers",
    true,
    true,
    false,
    "#e7e9e5",
    4.8,
    112,
    "A fresh pair for whatever the day brings. Clean lines, cushioned insoles, and a lightweight outsole for all-day comfort.",
    [
      "Cushioned insole",
      "Breathable lining",
      "Durable rubber sole",
      "Sizes EU 39–45; specify in notes",
    ],
  ],
  [
    "minimal-watch",
    "Classic Minimal Watch",
    "Fashion",
    42000,
    55000,
    "watch",
    false,
    true,
    true,
    "#eae8e3",
    4.9,
    73,
    "Time well spent. A refined analogue watch with a stainless steel case, clear dial, and comfortable leather strap.",
    [
      "Japanese quartz movement",
      "Stainless steel case",
      "Genuine leather strap",
      "3 ATM splash resistance",
    ],
  ],
  [
    "glow-serum",
    "Daily Glow Face Serum",
    "Beauty & Care",
    15500,
    20000,
    "serum",
    false,
    true,
    true,
    "#eaded1",
    4.8,
    92,
    "Make room for your morning ritual. A lightweight hydrating serum that leaves skin feeling soft, fresh, and cared for.",
    [
      "30 ml glass bottle",
      "Lightweight hydration",
      "Fragrance-free formula",
      "Patch test before first use",
    ],
  ],
  [
    "portable-speaker",
    "Pocket Bluetooth Speaker",
    "Electronics",
    26500,
    35000,
    "speaker",
    false,
    true,
    false,
    "#e2e6e2",
    4.7,
    61,
    "Good sound goes everywhere. A compact wireless speaker with rich audio and an easy-to-carry design.",
    [
      "Bluetooth 5.3",
      "12 hours of playtime",
      "USB-C charging",
      "IPX5 water resistance",
    ],
  ],
  [
    "ceramic-mug",
    "Sunday Ceramic Mug",
    "Home & Living",
    8500,
    12000,
    "mug",
    false,
    false,
    true,
    "#e8e3d8",
    4.9,
    38,
    "Slow mornings start here. A generously sized stoneware mug with a comfortable handle and a hand-glazed finish.",
    [
      "350 ml capacity",
      "Glazed stoneware",
      "Dishwasher safe",
      "Microwave safe",
    ],
  ],
  [
    "wireless-earbuds",
    "Air Wireless Earbuds",
    "Electronics",
    19500,
    28000,
    "earbuds",
    false,
    true,
    true,
    "#e9e9e7",
    4.6,
    147,
    "Your playlist, pocket-sized. Lightweight true wireless earbuds with a compact charging case and crisp calls.",
    [
      "Touch controls",
      "24-hour combined battery",
      "Comfortable silicone tips",
      "USB-C charging case",
    ],
  ],
  [
    "city-backpack",
    "The City Backpack",
    "Fashion",
    22500,
    30000,
    "backpack",
    false,
    false,
    true,
    "#e5e6df",
    4.8,
    49,
    "Made for your daily commute and spontaneous weekends. A lightweight backpack with thoughtful organisation.",
    [
      "Water-resistant fabric",
      "Padded laptop sleeve",
      "Multiple organiser pockets",
      "Comfortable padded straps",
    ],
  ],
  [
    "linen-tshirt",
    "Essential Cotton Tee",
    "Fashion",
    9500,
    13500,
    "tshirt",
    false,
    true,
    false,
    "#eee8df",
    4.7,
    204,
    "The wardrobe favourite you'll reach for again. Soft cotton, a relaxed fit, and a simple, versatile finish.",
    [
      "100% cotton",
      "Relaxed unisex fit",
      "Machine washable",
      "Sizes S–XXL; specify in notes",
    ],
  ],
  [
    "sunglasses",
    "Weekend Sunglasses",
    "Fashion",
    12000,
    16000,
    "glasses",
    false,
    false,
    true,
    "#e6dfd4",
    4.6,
    42,
    "A sunnier outlook. Lightweight frames and UV-protective lenses for comfortable everyday wear.",
    [
      "UV400 protection",
      "Lightweight frame",
      "Protective pouch included",
      "Unisex style",
    ],
  ],
  [
    "slim-wireless-keyboard", "Slim Wireless Keyboard", "Electronics", 38500, 49500, "keyboard",
    true, false, true, "#e9e8e2", 4.8, 37,
    "A calmer, cleaner workspace. A low-profile keyboard for comfortable everyday typing, with a compact layout that leaves room to think.",
    ["Compact desktop layout", "Low-profile keys", "Wireless connection", "Lightweight design"],
  ],
  [
    "precision-wireless-mouse", "Precision Wireless Mouse", "Electronics", 18000, 24000, "mouse",
    true, true, true, "#e8e7e2", 4.7, 58,
    "Small details, smoother days. A comfortable wireless mouse that keeps your desk tidy and your daily work moving.",
    ["Wireless desktop use", "Comfortable contoured shape", "Smooth scroll wheel", "Compact and easy to carry"],
  ],
  [
    "retro-instant-camera", "Retro Instant Camera", "Electronics", 95000, 120000, "camera",
    false, false, true, "#e8e7e5", 4.9, 24,
    "Make a memory you can hold. A playful instant camera for weekends, celebrations, and all the little moments in between.",
    ["Instant-print photography", "Classic retro silhouette", "Built-in flash", "Film sold separately"],
  ],
  [
    "mini-wireless-earbuds", "Mini Wireless Earbuds", "Electronics", 22500, 30000, "earbuds",
    false, false, true, "#e9e9e7", 4.7, 64,
    "A little music makes a big difference. Compact earbuds for your commute, calls, and a playlist that follows you everywhere.",
    ["Pocket charging case", "Wireless listening", "Touch playback controls", "Comfortable everyday fit"],
  ],
  [
    "weekender-backpack", "The Weekender Backpack", "Fashion", 26500, 34000, "backpack",
    false, true, true, "#e5e6df", 4.8, 72,
    "Pack a little possibility. A roomy everyday backpack for short trips, work days, and spontaneous plans.",
    ["Roomy main compartment", "Adjustable shoulder straps", "Front organiser pocket", "Lightweight woven fabric"],
  ],
  [
    "round-smartwatch", "Everyday Round Smartwatch", "Fashion", 36500, 48000, "steel-watch",
    true, false, true, "#e9e9e6", 4.6, 43,
    "Keep your day in view. A clean, round watch face and a comfortable strap bring a modern touch to your everyday style.",
    ["Round digital display", "Comfortable adjustable strap", "Everyday activity tracking", "Charging cable included"],
  ],
  [
    "classic-cotton-tee", "The Classic Cotton Tee", "Fashion", 8500, 12000, "tshirt",
    false, true, false, "#eee8df", 4.8, 116,
    "Simple, soft, and always useful. An easy cotton tee that works just as well on its own as it does layered.",
    ["Soft cotton fabric", "Classic crew neck", "Easy regular fit", "Sizes S–XXL; specify in notes"],
  ],
  [
    "city-sunglasses", "City Frame Sunglasses", "Fashion", 12500, 16500, "glasses",
    false, false, true, "#e6dfd4", 4.7, 36,
    "For bright days and better outfits. A timeless frame that adds a little polish to your everyday look.",
    ["Lightweight frame", "Comfortable nose bridge", "Protective pouch", "Unisex styling"],
  ],
  [
    "hydrate-bottle", "Hydrate Everyday Bottle", "Home & Living", 13500, 18000, "bottle",
    true, true, true, "#e5e9df", 4.9, 82,
    "A fresh start, one sip at a time. A reusable bottle in a calming green finish, ready for your desk or your day out.",
    ["Reusable bottle", "Screw-top lid", "Easy to carry", "Hand wash recommended"],
  ],
  [
    "calm-scented-candle", "Calm Evening Candle", "Home & Living", 11500, 15000, "candle",
    true, false, true, "#e8e1d4", 4.8, 53,
    "Make a little space to unwind. A softly scented candle that brings a warm glow to your favourite corner.",
    ["Reusable glass vessel", "Single cotton wick", "Soft ambient scent", "Never leave burning unattended"],
  ],
  [
    "breakfast-cup", "Breakfast Ceramic Cup", "Home & Living", 10500, 14500, "mug",
    false, false, true, "#e8e3d8", 4.7, 29,
    "Your morning ritual, made a little nicer. A tactile ceramic cup for slow coffee, warm tea, and quiet starts.",
    ["Glazed ceramic finish", "Comfortable handle", "Everyday drinkware", "Sold individually"],
  ],
  [
    "reading-table-lamp", "The Reading Table Lamp", "Home & Living", 21500, 28500, "lamp",
    false, true, false, "#eeeae3", 4.8, 46,
    "One more chapter. A compact table lamp that brings a soft pool of light to your bedside or reading nook.",
    ["Compact tabletop footprint", "Soft fabric shade", "Simple on/off switch", "Warm lighting"],
  ],
  [
    "signature-perfume", "Signature Everyday Perfume", "Beauty & Care", 29500, 38000, "perfume",
    false, true, true, "#ebded0", 4.8, 67,
    "A finishing touch for your day. An elegant fragrance bottle that feels at home on your dressing table.",
    ["Spray fragrance", "Glass bottle", "A thoughtful gift", "For external use only"],
  ],
  [
    "gentle-face-cleanser", "Gentle Daily Face Cleanser", "Beauty & Care", 12000, 15000, "cleanser",
    true, false, true, "#e8e5eb", 4.7, 51,
    "A simple step in your daily routine. A gentle-feeling face cleanser for a fresh, comfortable start and finish to the day.",
    ["Daily cleansing routine", "Easy squeeze tube", "Rinse-off formula", "Patch test before first use"],
  ],
  [
    "everyday-brush-set", "Everyday Makeup Brush Set", "Beauty & Care", 24500, 32000, "beauty",
    false, true, true, "#e9e0d8", 4.8, 34,
    "A little care in every detail. A versatile brush collection for blending, finishing, and your favourite everyday looks.",
    ["Brushes for face and eyes", "Soft synthetic bristles", "Easy-grip handles", "Clean regularly with mild soap"],
  ],
  [
    "botanical-body-oil", "Botanical Body Oil", "Beauty & Care", 18500, 25000, "serum",
    false, false, true, "#eaded1", 4.7, 41,
    "Turn a daily habit into a small ritual. A lightweight body oil that leaves your skin feeling cared for after a shower.",
    ["Lightweight body oil", "Glass dropper bottle", "Apply to damp skin", "Patch test before first use"],
  ],
  [
    "commute-headphones", "Commute Wireless Headphones", "Electronics", 59500, 79000, "headphones",
    false, false, true, "#eee9e1", 0, 0,
    "A comfortable companion for busy journeys. Wireless over-ear headphones with a foldable design, ready for your next listening session.",
    ["Wireless over-ear listening", "Foldable design", "Cushioned ear cups", "USB-C charging"],
  ],
  [
    "weekend-carryall", "Weekend Carryall Bag", "Fashion", 48000, 60000, "bag",
    false, false, true, "#eae4d9", 0, 0,
    "Carry a little more of your day. A roomy, structured bag with a simple silhouette and thoughtful everyday organisation.",
    ["Roomy main compartment", "Interior organiser pocket", "Comfortable shoulder straps", "Easy-care finish"],
  ],
  [
    "studio-desk-lamp", "Studio Desk Lamp", "Home & Living", 36000, 48000, "lamp",
    false, false, true, "#eeeae3", 0, 0,
    "Make your workspace feel warmer. A compact table lamp with a soft fabric shade for focused evenings and quiet corners.",
    ["Compact tabletop design", "Soft fabric shade", "Simple on/off switch", "Warm ambient light"],
  ],
] as const;
const soldOutProducts = new Set<string>(["commute-headphones", "weekend-carryall", "studio-desk-lamp"]);
export function demoProducts(): Product[] {
  const now = new Date();
  // Midnight in Lagos. Demo deadlines are sample campaigns, refreshed per day.
  const lagosEnd = new Date(
    Date.UTC(
      now.getUTCFullYear(),
      now.getUTCMonth(),
      now.getUTCDate() + (now.getUTCHours() >= 23 ? 2 : 1),
      -1,
    ),
  );
  return rows.map((r, i) => ({
    id: r[0],
    slug: r[0],
    title: r[1],
    category: r[2],
    priceNaira: r[3],
    originalPriceNaira: r[4],
    imageUrl: `/images/${r[5]}.webp`,
    isDailyDeal: r[6],
    isBestSeller: r[7],
    isNewArrival: r[8],
    color: r[9],
    rating: "0",
    reviewCount: 0,
    description: r[12],
    features: [...r[13]],
    stock: soldOutProducts.has(r[0]) ? 0 : 15 + i * 3,
    reserved: 0,
    dealEndsAt: r[6] ? lagosEnd.toISOString() : null,
  }));
}
export const CATEGORIES = [
  "All products",
  "Electronics",
  "Fashion",
  "Home & Living",
  "Beauty & Care",
];
